version: '3.8'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: server
    container_name: servidor1
    ports:
      - "9001:9000"
    environment:
      - INSTANCE_ID=1

  server2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: server
    container_name: servidor2
    ports:
      - "9002:9000"
    environment:
      - INSTANCE_ID=2

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: client
    container_name: cliente
    stdi_open: true
    tty: true
    depends_on:
      - server1
      - server2
    environment:
      - SERVER_ADDRESSES=servidor1:9000,servidor2:9000