services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1889:1883"
      - "9006:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
    networks:
      - appnet

  server1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: server
    container_name: servidor1
    depends_on:
      - mqtt
    ports:
      - "9007:9000"
    environment:
      - INSTANCE_ID=1
      - MQTT_BROKER=tcp://mqtt:1883
      - JSON_FILE=pontos1.json 
    volumes:
      - ./data:/app/data
    networks:
      - appnet

  server2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: server
    container_name: servidor2
    depends_on:
      - mqtt
    ports:
      - "9002:9000"
    environment:
      - INSTANCE_ID=2
      - MQTT_BROKER=tcp://mqtt:1883
      - JSON_FILE=pontos2.json
    volumes:
      - ./data:/app/data
    networks:
      - appnet

  server3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: server
    container_name: servidor3
    depends_on:
      - mqtt
    ports:
      - "9003:9000"
    environment:
      - INSTANCE_ID=3
      - MQTT_BROKER=tcp://mqtt:1883
      - JSON_FILE=pontos3.json 
    volumes:
      - ./data:/app/data
    networks:
      - appnet

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: client
    container_name: cliente
    stdin_open: true
    tty: true
    depends_on:
      - server1
      - server2
      - mqtt
    environment:
      - SERVER_ADDRESSES=servidor1:9000,servidor2:9000
      - MQTT_BROKER=tcp://mqtt:1883
    networks:
      - appnet
      
networks:
  appnet:
    driver: bridge
